//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarbonFootPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food_apparels_cloth_recycle_tips
    {
        public int foods_id { get; set; }
        public int apparels_id { get; set; }
        public int recycle_id { get; set; }
        public int tips_id { get; set; }
    
        public virtual Apparel Apparel { get; set; }
        public virtual Food Food { get; set; }
        public virtual Recycle Recycle { get; set; }
        public virtual Tip Tip { get; set; }
    }
}
