//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarbonFootPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.food_apparels_cloth_recycle_tips = new HashSet<food_apparels_cloth_recycle_tips>();
        }
    
        public int Id { get; set; }
        public string Category { get; set; }
        public float Energy_PER_100gm { get; set; }
        public float PER_SERVING_gm { get; set; }
        public float E1_ACFP_PER_100gm { get; set; }
        public float PROTEIN_PER_100gm { get; set; }
        public float E2_ACFP_PROTEIN_PER_100gm { get; set; }
        public float E3_ACFP_ENERGY_PER_100KCAL { get; set; }
        public string Image_Path { get; set; }
        public string Suggestions { get; set; }
        public int Category_Id { get; set; }

        public String nutrition { get; set; }
        public String frequency { get; set; }
        public float input { get; set; }
    
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<food_apparels_cloth_recycle_tips> food_apparels_cloth_recycle_tips { get; set; }
    }
}
