//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarbonFootPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recycle()
        {
            this.food_apparels_cloth_recycle_tips = new HashSet<food_apparels_cloth_recycle_tips>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public float Carbon_Footprint_Primary { get; set; }
        public float Carbon_Footprint_Secondary { get; set; }
        public float Footprint_Differences { get; set; }
        public string Image_Path { get; set; }
        public string Suggestions { get; set; }
        public int Category_Id { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<food_apparels_cloth_recycle_tips> food_apparels_cloth_recycle_tips { get; set; }
    }

    public class RecycleQuantity
    {
        public float glassQty { get; set; }
        public float aluminiumQty { get; set; }
        public float steelQty { get; set; }
        public float plasticsQty { get; set; }
        public float pcQty { get; set; }
        public float owcQty { get; set; }
        public float owdQty { get; set; }
    }

}
